logging:
  config: logback.xml
  level:
    com.test.caizq.demo:  info
    
#数据库地址
#datasource:
#  url: 192.168.1.12:3306/test_foshan    
server:
  address: 0.0.0.0


spring:
  profiles:
    active:
    - prod    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp14393ykqdzlu98j6o.mysql.rds.aliyuncs.com:3306/test_foshan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true 
    username: root
    password: 'Ld12121212'
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
mybatis:
  type-aliases-package: com.test.caizq.demo.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: 
    - classpath:mapper/*.xml
    
    